language: node_js
node_js:
  - "0.12"
after_success:
  - npm run deploy
notifications:
  slack:
    rooms:
      - cascadiafest:upIkrnH6MWQ3K75VTBBrFkkx#design-and-web
    on_success: always
    on_start: always