language: node_js
node_js:
  - "4.2"
env:
  - CXX=g++-4.8
deploy:
  provider: script
  script: npm run deploy
  on:
    branch: master
notifications:
  slack: cascadiafest:upIkrnH6MWQ3K75VTBBrFkkx
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8